In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
sns.set(style='whitegrid')

In [3]:
df = pd.read_csv(r'actor_vial.csv')

In [ ]:
len(df)

In [5]:
df['CONDICION'].unique()

array(['CONDUCTOR', 'PEATON', 'PASAJERO', 'MOTOCICLISTA', 'CICLISTA'],
      dtype=object)

In [14]:
df1 = pd.read_csv(r'siniestros.csv')

In [15]:
df1[(df1['CODIGO_SINIESTRO']==4425548)]

,Unnamed: 0,CODIGO_SINIESTRO,FECHA,HORA,GRAVEDAD,CLASE,CHOQUE_CON,OBJETO_FIJO,DIRECCION,TOTAL_MUERTOS,TOTAL_HERIDOS,LOCALIDAD,DISENO_LUGAR
23570,23570,4425548,02/10/2015,08:00:00,Con Muertos,Choque,Vehiculo,NaN,AV AVENIDA JORGE GAITAN CORTES-CL 58A S 02,1,72,Ciudad Bolívar,Tramo de Via

In [53]:
peaton_fallecido = pd.DataFrame(df[(df['ESTADO']=='MUERTO') & (df['CONDICION']=='PEATON')].groupby(
    ['CODIGO_SINIESTRO','CONDICION'])['CONDICION'].count().reset_index(name='PEATON_FALLECIDO'))

peaton_herido = pd.DataFrame(df[(df['ESTADO']=='HERIDO') & (df['CONDICION']=='PEATON')].groupby(
    ['CODIGO_SINIESTRO','CONDICION'])['CONDICION'].count().reset_index(name='PEATON_HERIDO'))

pasajero_fallecido = pd.DataFrame(df[(df['ESTADO']=='MUERTO') & (df['CONDICION']=='PASAJERO')].groupby(
    ['CODIGO_SINIESTRO','CONDICION'])['CONDICION'].count().reset_index(name='PASAJERO_FALLECIDO'))

pasajero_herido = pd.DataFrame(df[(df['ESTADO']=='HERIDO') & (df['CONDICION']=='PASAJERO')].groupby(
    ['CODIGO_SINIESTRO','CONDICION'])['CONDICION'].count().reset_index(name='PASAJERO_HERIDO'))

conductor_fallecido = pd.DataFrame(df[(df['ESTADO']=='MUERTO') & (df['CONDICION']=='CONDUCTOR')].groupby(
    ['CODIGO_SINIESTRO','CONDICION'])['CONDICION'].count().reset_index(name='CONDUCTOR_FALLECIDO'))

conductor_herido = pd.DataFrame(df[(df['ESTADO']=='HERIDO') & (df['CONDICION']=='CONDUCTOR')].groupby(
    ['CODIGO_SINIESTRO','CONDICION'])['CONDICION'].count().reset_index(name='CONDUCTOR_HERIDO'))

motociclista_fallecido = pd.DataFrame(df[(df['ESTADO']=='MUERTO') & (df['CONDICION']=='MOTOCICLISTA')].groupby(
    ['CODIGO_SINIESTRO','CONDICION'])['CONDICION'].count().reset_index(name='MOTOCICLISTA_FALLECIDO'))

motociclista_herido = pd.DataFrame(df[(df['ESTADO']=='HERIDO') & (df['CONDICION']=='MOTOCICLISTA')].groupby(
    ['CODIGO_SINIESTRO','CONDICION'])['CONDICION'].count().reset_index(name='MOTOCICLISTA_HERIDO'))

ciclista_fallecido = pd.DataFrame(df[(df['ESTADO']=='MUERTO') & (df['CONDICION']=='CICLISTA')].groupby(
    ['CODIGO_SINIESTRO','CONDICION'])['CONDICION'].count().reset_index(name='CICLISTA_FALLECIDO'))

ciclista_herido = pd.DataFrame(df[(df['ESTADO']=='HERIDO') & (df['CONDICION']=='CICLISTA')].groupby(
    ['CODIGO_SINIESTRO','CONDICION'])['CONDICION'].count().reset_index(name='CICLISTA_HERIDO'))

del(peaton_fallecido['CONDICION'])
del(peaton_herido['CONDICION'])
del(pasajero_fallecido['CONDICION'])
del(pasajero_herido['CONDICION'])
del(conductor_fallecido['CONDICION'])
del(conductor_herido['CONDICION'])
del(motociclista_fallecido['CONDICION'])
del(motociclista_herido['CONDICION'])
del(ciclista_fallecido['CONDICION'])
del(ciclista_herido['CONDICION'])

In [ ]:
display(peaton_fallecido.head(2))
display(peaton_herido.head(2))
display(pasajero_fallecido.head(2))
display(pasajero_herido.head(2))
display(conductor_fallecido.head(2))
display(conductor_herido.head(2))
display(motociclista_fallecido.head(2))
display(motociclista_herido.head(2))
display(ciclista_fallecido.head(2))
display(ciclista_herido.head(2))

In [55]:
df.head()

   CODIGO_SINIESTRO     FECHA  CONDICION  ESTADO  EDAD       SEXO   VEHICULO
0           4401420  1/1/2015  CONDUCTOR   ILESO  20.0  MASCULINO  4401420-2
1           4401429  1/1/2015     PEATON  HERIDO  28.0  MASCULINO        NaN
2           4401442  1/1/2015   PASAJERO  HERIDO  22.0  MASCULINO  4401442-1
3           4401442  1/1/2015     PEATON  HERIDO  57.0  MASCULINO        NaN
4           4401423  1/1/2015     PEATON  HERIDO  19.0   FEMENINO        NaN

In [63]:
print('siniestros con peaton fallecido: ',len(peaton_fallecido))
print('siniestros con peaton herido: ',len(peaton_herido))
print('siniestros con pasajero fallecido: ',len(pasajero_fallecido))
print('siniestros con pasajero herido: ',len(pasajero_herido))
print('siniestros con ciclista fallecido: ',len(ciclista_fallecido))
print('siniestros con ciclista herido: ',len(ciclista_herido))
print('siniestros con motociclista fallecido: ',len(motociclista_fallecido))
print('siniestros con motociclista herido: ',len(motociclista_herido))
print('siniestros con conductor fallecido: ',len(conductor_fallecido))
print('siniestros con conductor herido: ',len(conductor_herido))

siniestros con peaton fallecido:  1288
siniestros con peaton herido:  18462
siniestros con pasajero fallecido:  257
siniestros con pasajero herido:  16867
siniestros con ciclista fallecido:  326
siniestros con ciclista herido:  7921
siniestros con motociclista fallecido:  744
siniestros con motociclista herido:  23037
siniestros con conductor fallecido:  54
siniestros con conductor herido:  4410

In [269]:
df_sexo = df[['CODIGO_SINIESTRO', 'SEXO']].copy()

In [270]:
z = pd.DataFrame(df_sexo.groupby(
    ('CODIGO_SINIESTRO','SEXO'))['SEXO'].count().reset_index(name='CANTIDAD'))

z=z.pivot_table(
    index='CODIGO_SINIESTRO', columns='SEXO', values='CANTIDAD', fill_value = 0).reset_index()

z.rename_axis('', axis = 'columns', inplace=True)

C:\Users\57321\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Interpreting tuple 'by' as a list of keys, rather than a single key. Use 'by=[...]' instead of 'by=(...)'. In the future, a tuple will always mean a single key.

In [271]:
actor_vial_sin_edad =  pd.merge(z, peaton_fallecido, how='outer' )
actor_vial_sin_edad = pd.merge(actor_vial_sin_edad, peaton_herido, how='outer')

actor_vial_sin_edad = pd.merge(actor_vial_sin_edad, pasajero_fallecido, how='outer')
actor_vial_sin_edad = pd.merge(actor_vial_sin_edad, pasajero_herido, how='outer')

actor_vial_sin_edad = pd.merge(actor_vial_sin_edad, conductor_fallecido, how='outer')
actor_vial_sin_edad = pd.merge(actor_vial_sin_edad, conductor_herido, how='outer')

actor_vial_sin_edad = pd.merge(actor_vial_sin_edad, ciclista_fallecido, how='outer')
actor_vial_sin_edad = pd.merge(actor_vial_sin_edad, ciclista_herido, how='outer')

actor_vial_sin_edad = pd.merge(actor_vial_sin_edad, motociclista_fallecido, how='outer')
actor_vial_sin_edad = pd.merge(actor_vial_sin_edad, motociclista_herido, how='outer')

In [272]:
len(z)

173306

In [273]:
len(actor_vial_sin_edad)

173306

In [274]:
actor_vial_sin_edad.head().T

                                0          1          2          3          4
CODIGO_SINIESTRO        4401419.0  4401420.0  4401421.0  4401422.0  4401423.0
FEMENINO                      1.0        0.0        1.0        0.0        1.0
MASCULINO                     1.0        2.0        2.0        2.0        1.0
SIN INFORMACION               0.0        0.0        0.0        0.0        1.0
PEATON_FALLECIDO              NaN        NaN        NaN        NaN        NaN
PEATON_HERIDO                 NaN        NaN        2.0        NaN        1.0
PASAJERO_FALLECIDO            NaN        NaN        NaN        NaN        NaN
PASAJERO_HERIDO               1.0        NaN        NaN        NaN        NaN
CONDUCTOR_FALLECIDO           NaN        NaN        NaN        NaN        NaN
CONDUCTOR_HERIDO              NaN        NaN        NaN        NaN        1.0
CICLISTA_FALLECIDO            NaN        NaN        NaN        NaN        NaN
CICLISTA_HERIDO               NaN        NaN        NaN        1.0        NaN
MOTOCICLISTA_FALLECIDO        NaN        NaN        NaN        NaN        NaN
MOTOCICLISTA_HERIDO           NaN        NaN        NaN        NaN        NaN

In [275]:
actor_vial_sin_edad.fillna(0, inplace=True)

In [276]:
actor_vial_sin_edad['ILESOS'] = actor_vial_sin_edad.iloc[:,1:3].sum(axis=1) - actor_vial_sin_edad.iloc[:,4:].sum(axis=1)

In [284]:
actor_vial_sin_edad

,CODIGO_SINIESTRO,FEMENINO,MASCULINO,SIN INFORMACION,PEATON_FALLECIDO,PEATON_HERIDO,PASAJERO_FALLECIDO,PASAJERO_HERIDO,CONDUCTOR_FALLECIDO,CONDUCTOR_HERIDO,CICLISTA_FALLECIDO,CICLISTA_HERIDO,MOTOCICLISTA_FALLECIDO,MOTOCICLISTA_HERIDO,ILESOS
0,4401419,1,1,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,4401420,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
2,4401421,1,2,0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4401422,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,4401423,1,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5,4401424,0,2,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,4401425,1,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
7,4401426,0,3,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
8,4401427,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
9,4401428,2,2,0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
10,4401429,0,2,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11,4401430,0,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
12,4401431,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
13,4401432,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
14,4401433,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
15,4401434,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
16,4401435,1,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
17,4401436,3,3,0,0.0,0.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
18,4401437,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
19,4401438,0,2,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
20,4401439,1,2,0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
21,4401440,0,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
22,4401441,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
23,4401442,0,3,0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
24,4401443,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
25,4401444,2,2,0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
26,4401445,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
27,4401446,2,2,0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
28,4401447,1,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
29,4401448,0,2,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173276,10507435,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173277,10507436,1,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173278,10507437,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173279,10507438,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173280,10507439,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173281,10507440,1,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173282,10507441,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173283,10507442,1,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173284,10507443,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173285,10507444,1,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173286,10507445,1,2,0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
173287,10507446,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173288,10507447,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173289,10507448,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173290,10507449,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
173291,10507450,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173292,10507451,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173293,10507452,0,3,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
173294,10507854,0,2,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
173295,10507855,0,2,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
173296,10508852,1,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173297,10508918,0,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
173298,10511408,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
173299,10513493,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173300,10513514,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
173301,10513519,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
173302,10514267,1,1,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
173303,10514268,0,0,2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0
173304,10514269,0,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
173305,10514270,0,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [279]:
actor_vial_sin_edad.to_csv('actor_vial_sin_edad.csv', index=None)

In [283]:
actor_vial_sin_edad['ILESOS'].sum()

281616.0